name: ${COMPOSE_PROJECT_NAME:-telemetry-processor-service}

services:
  kafka-telemetry-clean-ws:
    build:
      context: ..
      dockerfile: docker/python/Dockerfile
    env_file:
      - ../.env
    image: iot-hub-kafka-telemetry-clean-ws
    container_name: kafka-telemetry-clean-ws
    command: [ "python", "-m", "src.consumers.telemetry_validator" ]
    environment:
      KAFKA_GROUP_ID: telemetry-clean-ws
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - iot-hub-nw

networks:
  iot-hub-nw:
    external: true
